### ISSUE TITLE
Extract the `?-leveldown` wrapper

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/indexd#1]
... to a 3rd party module.

~~Note that a `.Value` type can be used now instead of the `.prefix`~~
Added in https://github.com/dcousens/indexd/commit/d3e6fe90eaaa923d827c07765a47879c5757206d

**Comment by dcousens** [comment]
@dominictarr @fanatid would this be a candidate for the organization?
I'm not sure myself,  but I figured it might be a question worth asking.

Ref: https://github.com/dcousens/indexd/blob/master/ldb.js

**Comment by dcousens** [comment]
Maybe not actually... its more related to abstract encoding then it is to `varstruct` specifically.

**Comment by dominictarr** [comment]
I'm happy for this be in the org

**Comment by dcousens** [comment]
As is,  it is a `abstract-leveldown` (aka, conforming to the interface provided by `leveldown`) wrapper rather than `levelup` to avoid the 5-6 abstractions deep [`level-codec`](https://github.com/level/codec)/`levelup` encoding/decoding.
