### ISSUE TITLE
(Trivial) Inconsistent date format in logs

### ISSUE THREAD

**Issue by unsystemizer** [bitcoinjs/indexd#23]
In some cases such as this one below, certain components use a different date format. Probably something from upstream, in which case feel free to close.
```
2017-10-30T14:35:27.153Z zmq:tx hashtx ef108ac19e62d4b2c3c0adfb4a8dde787a41abde0                                                                                     6e02bcab907980c41b9821f
Mon, 30 Oct 2017 14:35:27 GMT mempool { transactions: 284, inputs: 450, outputs: 505 }
```

**Comment by dcousens** [comment]
I can only assume this is upstream... but how odd.
Both are using `debug`?

**Comment by dcousens** [comment]
Is it possible your local `debug` is different to what has been required in this package?
(https://github.com/bitcoinjs/indexd/blob/master/package.json#L7)

Maybe we should make it an optional dependency and allow `*`?

**Comment by dcousens** [comment]
Namespaced `debug` and made it optional in 0a07d06 - re-open if not fixed

**Comment by unsystemizer** [comment]
Ok. I checked and run-parallel seems correct and installed. I just updated and re-checked other deps, so I'll reopen if I spot this again.
```
root@indexd:/indexd/node_modules/run-parallel# cat package.json | grep version
  "version": "1.1.6"
```
