### ISSUE TITLE
how to use indexd

### ISSUE THREAD

**Issue by KanoczTomas** [bitcoinjs/indexd#24]
Hello,

from the issues I read I found out perhaps I am not using the indexd module correctly. There is a standalone index server as I could read, is this a module for it?

In the previous commit (53506f08ef77bcdca3fb6230a5aea84c3fbaa875) I could run node test/index.js and the index leveldb would be populated with debug output visible on the console.

When using the latest commit I can do queries navigating to express example page, but I do not see the db being populated anymore. 

Would like to ask your kind help in setting it up, or pointing me to a readme where it is noted how to run it.

**Comment by dcousens** [comment]
@KanoczTomas I'll add a `npm run` target to start the `example/` service/server.

**Comment by KanoczTomas** [comment]
That would be cool! I found out that the db was actually populated, but there was no debug output eventhough I had DEBUG=* in my .env. After doing export DEBUG=* in the terminal and running the example afterwards I saw all debug messages. I might be doing something wrong that DEBUG is not being applied from .env ...

**Comment by dcousens** [comment]
`npm start` should work now as is (ensure you `npm i` prior to install `devDependencies`)
