### ISSUE TITLE
messages lost

### ISSUE THREAD

**Issue by MajorChump** [bitcoinjs/indexd#34]
I see a ton of

zmq 866 messages lost +133ms
  zmq 227 messages lost +1s
  zmq 534 messages lost +152ms
  zmq 205 messages lost +128ms
  zmq 523 messages lost +7ms
  zmq 976 messages lost +136ms
  zmq 996 messages lost +329ms
  zmq 425 messages lost +495ms
  zmq 721 messages lost +4ms
  zmq 1015 messages lost +147ms
  zmq 486 messages lost +146ms
  zmq 157 messages lost +294ms
  zmq 1072 messages lost +478ms
  zmq 624 messages lost +4ms
  zmq 1178 messages lost +141ms
  zmq 818 messages lost +145ms
  zmq 824 messages lost +340ms
  zmq 301 messages lost +166ms
  zmq 231 messages lost +139ms
  zmq 739 messages lost +3ms
  zmq 856 messages lost +126ms

When its sycning up, I assume this is handled and is just for debug purposes or are the indexes incomplete if this appears?

**Comment by dcousens** [comment]
@MatthewKingDev it is intentional,  and is how we **trigger** the `resync` process.

It does not impact the completeness of the indexes in any way.

**Comment by MajorChump** [comment]
Perfect thanks!
