### ISSUE TITLE
Resource temporarily unavailable

### ISSUE THREAD

**Issue by brmdbr** [bitcoinjs/indexd#42]
I'm getting the following error using the example code when starting indexd:
` /root/.bitcoin/chainstate/LOCK: Resource temporarily unavailable`

I'm on centos 7, same configuration has worked for me on an ubuntu server a while back. Anyone got an idea?

**Comment by dcousens** [comment]
@BramdeBoer do you have available disk-space?
IIRC,  that error occurs if the `LOCK` could not be created by `bitcoind`.
