### ISSUE TITLE
Bitcoind crashed without error

### ISSUE THREAD

**Issue by brmdbr** [bitcoinjs/indexd#43]
Hello, my bitcoin node (v0.16.99.0-e057589) crashes without throwing an error while syncing indexd. It happens after a few hours and is really frustrating. I'm using the latest release in this server but I figured it probably is an indexd issue: https://github.com/CounterpartyXCP/indexd-server

bitcoin.conf
```
listen=1
rpcuser=xxxxxxxxxxxxx
rpcpassword=xxxxxxxxxxxx
rpcport=8332
rpcconnect=127.0.0.1
rpcallowip=222.22.22.22
rpcallowip=127.0.0.1
rpcallowip=22.222.222.22
zmqpubhashtx=tcp://127.0.0.1:38832
zmqpubhashblock=tcp://127.0.0.1:38832
server=1
txindex=1
addrindex=1
walletbroadcast=0
daemon=1
rpcthreads=16
rpcworkqueue=32
```

**Comment by dcousens** [comment]
@BramdeBoer can you post the debug log?

**Comment by brmdbr** [comment]
The debug.log, not sure if anything intrestring in there.

[https://pastebin.com/T830Qg8k](url)

**Comment by dcousens** [comment]
Can you reproduce the crash?

**Comment by brmdbr** [comment]
It happens after a few hours (maybe even less, it seems to be happening faster every time) every time I start bitcoind and indexd-server. It doesn't give any notable errors as you've probably seen.

**Comment by dcousens** [comment]
@BramdeBoer maybe post the bug report at https://github.com/bitcoin/bitcoin ?  Feel free to tag me and this issue.
The only parts `indexd` typically uses of `bitcoind` is the RPC and ZMQ,  so the error likely rests there.

**Comment by brmdbr** [comment]
@dcousens Thanks for your help Daniel, I made an issue: https://github.com/bitcoin/bitcoin/issues/12773
