### ISSUE TITLE
Suitability in bitcoinjs organization

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/indexd#5]
Thoughts @fanatid? @jprichardson

This is an alternative to insight or the like,  in that it uses the mainline https://github.com/bitcoin/bitcoin RPC and software,  not a modified version.

* Script Index (ala, address index)
* Spents Index (ala, inverse of unspents)
* TxOuts Index
* TxHeight Index

It still uses the `txindex` in `bitcoin-core` (as moving that out would duplicate a lot of data),  and we can either use the soon-to-be-added unspents index as in https://github.com/bitcoin/bitcoin/pull/9806,   or we can trivially add our own (probably ideal tbh).

**Comment by jprichardson** [comment]
Yeah, I think it makes sense to move over.

My biggest question would be: what was the biggest motivator for you writing it?

**Comment by dcousens** [comment]
@jprichardson I don't like running https://github.com/bitcoin/bitcoin forks;  I don't have the manpower to vett my changes continuously,  or that of an un-maintained fork.

I wanted something that I could easily play with,  add indexes,  remove indexes,  without dabbling with my consensus mechanism.
Easily add leveldb address-clustering indexes,  etc.

I wanted something easy to review,  less than 600 lines of code (less,  ideally).

I wanted something to replace systems quickly becoming legacy in various production environments.

I know this is a common problem in the community,   where that ol' `addrindex` fork is still used,  and keeps some companies from upgrading their bitcoin software.

**Comment by jprichardson** [comment]
Ah, makes sense!

**Comment by dcousens** [comment]
Moved :+1:
