### ISSUE TITLE
REST API + Block Explorer website

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/indexd#8]
Probably best suited to an external module

**Comment by KanoczTomas** [comment]
Hi, do you think your indexd can be integrated to this?
https://github.com/KanoczTomas/01Cnode

demopage at http://node.ispol.sk (after implementing fee querying the site is pretty much unstable, as bitcoin core crashes here and then)

Right now I have an issue with killing bitcoind byt too much RPC. your indexd sounds like a solution!
Am not a very experienced JS coder though, so will have to go through your code to fully understand it. Is there a way to reach you in case I need clarification?

Ah and a very nice project! :) All bitcoinjs ... using it to decode txes for mempool view ...
TY!

**Comment by dcousens** [comment]
@KanoczTomas please see [this example](https://github.com/bitcoinjs/indexd/tree/dfce68e72587d0ba79546b1c70a678447d20ddff/example) using `express`.

**Comment by deweller** [comment]
This isn't an explorer, but a full API server for (U)TXOs by address is here:

https://github.com/CounterpartyXCP/indexd-server

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/private-bitcoin/

**Comment by dcousens** [comment]
@deweller if you want,  add https://github.com/CounterpartyXCP/indexd-server to the list of servers implemented using `indexd`?
