### ISSUE TITLE
Median time past index

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/indexd#9]
@runn1ng I assume this is what you mean by `timestamp` index?
I'll push up this,  as its only in my local fork of `indexd` atm...

**Comment by dcousens** [comment]
@runn1ng - are you literally just wanting `txId | utc` as a first-seen?
Would you also want `scId | utc`? Mind you,  that could be a huge chunk of data and would be a 2nd order insertion.

Maybe even `blockId | height | utc`?
Then you could track how many orphans occur.

That said,  each of these indexes would be re-org independent, and would continuously persist (obviously).

That said, all these could be optional.

**Comment by karelbilek** [comment]
From documentation of bitcore

> timestampindex
> 
> This index maps timestamps with block hashes and is useful for searching blocks by date instead of by height. This is useful for a block explorer that will give search options by date. However it should be noted that the timestamps of blocks can be out of order, as there is a tolerance of around 2 hours that a timestamp of block is allowed to be set.

So it's not first seen, but really time -> blockhash.

https://github.com/bitcoin/bitcoin/pull/10370/commits/2045ffebe1c885af2a2543eaa709da732f514577#diff-81e4f16a1b5d5b7ca25351a63d07cb80R269

https://github.com/bitcoin/bitcoin/pull/10370/commits/2045ffebe1c885af2a2543eaa709da732f514577#diff-24efdb00bfbe56b140fb006b562cc70bR2161

**Comment by dcousens** [comment]
When is that useful? OOI
I mean, its a trivial index to add

**Comment by karelbilek** [comment]
You deleted your message :) but well... bitcore uses it for displaying blocks on certain date, that's all

https://insight.bitpay.com/blocks-date/2017-03-06

But really it's not a must-have feature in the end, I guess

**Comment by dcousens** [comment]
@runn1ng sorry,  I realised you already addressed my question with:

> This is useful for a block explorer that will give search options by date

Apologies for the confusion.

**Comment by dcousens** [comment]
Added in https://github.com/bitcoinjs/indexd/pull/37 (query functions are missing, but, you can trivially make a PR! :) )

https://github.com/bitcoinjs/indexd/pull/37/commits/48a97bd
